Run("WinPcap_4_1_3.exe")
WinWaitActive("WinPcap 4.1.3 Setup")
Send("!n")
WinWaitActive("WinPcap 4.1.3 Setup", "Welcome to the WinPcap")
Send("!n")
WinWaitActive("WinPcap 4.1.3 Setup", "License Agreement")
Send("{ENTER}")
WinWaitActive("WinPcap 4.1.3 Setup", "Installation options")
ControlClick("WinPcap 4.1.3 Setup", "Installation options", "[CLASS:Button; INSTANCE:2]") ; hack to click the install button
WinWaitActive("WinPcap 4.1.3 Setup", "Completing the WinPcap")
Send("!f")